#!/bin/sh

# Copyright (c) 2015-2016 Stefan Tatschner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

VERSION="0.2.0"

usage() {
    echo "usage: $(basename $0) [-hV] COMMAND [<args>]"
    echo ""
    echo "commands:"
    echo "  init      Init snap directory structure"
    echo "  create    Create a new snapshot"
    echo "  prune     Prune existing snapshots"
    echo "  list      Show a list of available snap snapshots"
}

version() {
    echo "$(basename $0) $VERSION"
}

while getopts "hV" arg; do
    case $arg in
        h)  usage   && exit 0;;
        V)  version && exit 0;;
    esac
done

cmd="$1"
shift

# Catch empty $cmd
if [ -z $cmd ]; then
    usage
    exit 1
fi

if which "snap-$cmd" >& /dev/null; then
    exec "snap-$cmd" "$@"
fi

if [ -e "./snap-$cmd" ]; then
    exec "./snap-$cmd" "$@"
fi

usage
