#!/bin/sh

# Copyright (c) 2015-2016 Stefan Tatschner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    echo "usage: $(basename $0) [-lh] TARGET"
    echo ''
    echo 'common options:'
    echo '  -l           Only list subvolumes; no dates column'
    echo '  -h           Show this page and exit'
}

while getopts "hl" arg; do
    case "$arg" in
        l) NODATES="yes";;
        h) usage && exit 0;;
        *) usage && exit 1;;
    esac
done

shift $((OPTIND - 1))

[ -z "$1" ] && usage && exit 1

if [ "$NODATES" = "yes" ]; then
    btrfs subvolume list -os "$1" | awk '{print "/" $14}'
else
    btrfs subvolume list -os "$1" | awk '{print $11 " " $12 "\t" "/" $14}'
fi
